### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by hsjlyj** [Lupeiwen0/ChatGPT-UI#2]
当我运行npm run dev时出现以下报错:
> chat-gpt-ui@1.0.0 dev
> vite

file:///root/ChatGPT-UI/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
npm ERR! code 1
npm ERR! path /root/ChatGPT-UI
npm ERR! command failed
npm ERR! command sh -c vite

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-04-05T04_46_19_451Z-debug.log

**Comment by Lupeiwen0** [comment]
看上去应该是vite 的报错，重新安装 node_modules 依赖

兼容性注意
Vite 需要 [Node.js](https://nodejs.org/en/) 版本 14.18+，16+。然而，有些模板需要依赖更高的 Node 版本才能正常运行，当你的包管理器发出警告时，请注意升级你的 Node 版本。

**Comment by Lupeiwen0** [comment]
也可能是你放在了 root 目录，vite脚本 没有权限读写文件。

**Comment by hsjlyj** [comment]
非常感谢已经解决了 是nodejs版本问题 apt源里的太低了 我使用源码安装了最新版 希望可以加入自动化脚本
